web/auth.py
from flask import Blueprint, render_template, flash, request, redirect, url_for
from .webforms import UserForm, LoginForm, PasswordForm
from .models import Users
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import login_user, logout_user, login_required, current_user
from mongoengine.errors import DoesNotExist
from bson import ObjectId



auth = Blueprint('auth', __name__)


# LOGIN USER
@auth.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()

    # VALIDATE FORM FOR LOGIN
    if form.validate_on_submit():
        user = Users.objects(username=form.username.data).first()

        if user:
            # CHECK PASSWORD HASH
            if check_password_hash(user.password_hash, form.password.data):
                login_user(user)
                if user.username == "admin":
                    flash("Welcome Admin!", category='success')
                else:
                    flash(f"Welcome {user.username} - Logged In!", category='success')
                return redirect(url_for('root.dashboard'))
            else:
                flash("Wrong Password! - Try Again", category='error')
        else:
            flash("Invalid Username!", category='error')

        # CLEAR FORM
        form.username.data = ''

    return render_template('view/login.html',
                           form=form)


# LOGOUT USER
@auth.route("/logout")
@login_required
def logout():
    logout_user()
    flash("Logged Out!", category='success')
    return redirect(url_for('routes.home'))


# REGISTER USER
@auth.route('/register', methods=['GET', 'POST'])
@login_required
def register():
    name = None
    form = UserForm()

    # CHECK IF ADMIN
    if current_user.username == "admin": 
    # VALIDATE FORM DATA
        if form.validate_on_submit():
            # QUERY DB FOR CHECKING IF USER ALREADY EXISTS
            user = Users.objects(username=form.username.data).first()
            
            if user is None:
                # HASH PASSWORD
                hashed_pw = generate_password_hash(form.password_hash.data)

                # USER DATA TO INSERT INTO DB
                user = Users(name=form.name.data,
                            username=form.username.data,
                            email=form.email.data,
                            password_hash=hashed_pw)
                
                # INSERT RECORD INTO DB
                user.save()

            # ASSIGN NAME VALUE
            name = form.name.data

            # CLEAR FORM
            form.name.data = ''
            form.username.data = ''
            form.email.data = ''

            # RETURN A MESSAGE
            flash("User Registered!", category='success')
            return redirect(url_for('auth.users'))

        our_users = Users.objects.order_by('-date_added')

        return render_template('view/register.html',
                            form=form,
                            name=name,
                            our_users=our_users)
    
    else:
        flash("Sorry! You Are Not Authorized For This Action...", category='error')
        return redirect(url_for('root.dashboard'))


# EDIT/UPDATE USER
@auth.route('/user/<string:id>/update', methods=['GET', 'POST'])
@login_required
def update_user(id):
    form = UserForm()

    try:
        name_to_update = Users.objects.get(id=ObjectId(id))
    except DoesNotExist:
        flash("User not found", category='error')
        return redirect(url_for('root.dashboard'))

    if request.method == 'POST':

        name_to_update.name = request.form['name']
        name_to_update.username = request.form['username']
        name_to_update.email = request.form['email']

        try:
            name_to_update.save()
            flash("User Updated!", category='success')
            return redirect(url_for('root.dashboard'))

        except:
            flash("Error Updating User!", category='error')
            return render_template('view/update_user.html',
                                form=form,
                                name_to_update=name_to_update)
    else:
        return render_template('view/update_user.html',
                            form=form,
                            name_to_update=name_to_update,
                            id=id)
    

# DELETE USER
@auth.route('/user/<string:id>/delete')
@login_required
def delete_user(id):

    # ONLY ADMIN AND THE SPECIFIC ID USER CAN DELETE THEIR PROFILE
    if str(current_user.id) == id or current_user.username == 'admin':
        try:
            user_to_delete = Users.objects.get(id=ObjectId(id))
            user_to_delete.delete()

            if current_user.username == 'admin':
                flash("User Deleted!", category='success')
                return redirect(url_for('auth.users'))
            else:
                logout_user()
                flash("Account Deleted! Logged Out!", category='success')
                return redirect(url_for('routes.home'))

        except DoesNotExist:
            flash("User Not Found!", category='error')
            return redirect(url_for('auth.users'))
        
    else:
        flash("You Don't Have Access To This User", category='error')
        return redirect(url_for('root.dashboard'))


# RESET USER PASSWORD
@auth.route('/user/<string:id>/password-reset', methods=['GET', 'POST'])
@login_required
def reset_password(id):
    form = PasswordForm()

    try:
        user_password_reset = Users.objects.get(id=ObjectId(id))
    except DoesNotExist:
        flash("User Not Found", category='error')
        return redirect(url_for('auth.users'))

    if form.validate_on_submit():
        reset_hashed_pw = generate_password_hash(form.reset_password_hash.data)

        user_password_reset.password_hash = reset_hashed_pw

        try:
            user_password_reset.save()
            flash("Password Changed!", category='success')
            return redirect(url_for('root.dashboard'))
        
        except:
            flash("Error Changing Password!", category='error')
            return render_template('view/change_user_password.html',
                                   form=form)

    else:
        return render_template('view/change_user_password.html',
                           form=form,
                           id=id,
                           user_password_reset=user_password_reset)
    

# DISPLAY ALL USERS
@auth.route('/users')
@login_required
def users():

    # GET ALL EXISTING USERS FROM DB
    users = Users.objects.order_by('-date_added')

    return render_template('view/display_users.html',
                           users=users)

web/routes.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from .models import Products, Feedback, Categories, Review
from .webforms import FeedbackForm, ReviewForm
from mongoengine.errors import DoesNotExist
from bson import ObjectId
import random
from datetime import datetime



routes = Blueprint('routes', __name__)


# HOME PAGE
@routes.route('/')
def home():

    bestsellers = Products.objects.order_by('title')
    reviews = Review.objects()[:2]

    return render_template('view/home.html',
                           bestsellers=bestsellers,
                           reviews=reviews)


# INDIVIDUAL PRODUCT
@routes.route('/item/<string:id>')
def item(id):

    # GET PRODUCT BY ID
    try:
        item = Products.objects.get(id=ObjectId(id))
    except DoesNotExist:
        flash("Product not found!", category='error')
        return redirect(url_for('routes.home'))

    return render_template('view/item.html',
                           item=item)


# ABOUT US PAGE
@routes.route('/about')
def about():
    return render_template('view/about.html')


# CONTACT US PAGE
@routes.route('/contact', methods=['GET', 'POST'])
def contact():
    form = FeedbackForm()

    if form.validate_on_submit():
        feedback = Feedback(name=form.name.data,
                            phone_number=form.phone_number.data,
                            message=form.message.data)
        
        feedback.save()
        flash("Feedback Submitted!", category='success')
        return redirect(url_for('routes.contact'))

    return render_template('view/contact.html',
                           form=form)


# STORE PAGE
@routes.route('/store')
def store():

    categories = list(Categories.objects())

    first_category = None
    other_categories = []

    for category in categories:
        if category.type.lower() == "quick customization":
            first_category = category
        else:
            other_categories.append(category)

    if first_category:
        ordered_categories = [first_category] + other_categories
    else:
        ordered_categories = other_categories

    return render_template('view/store.html',
                           category=ordered_categories)


# PRODUCT UNDER A CATEGORY
@routes.route('/category/<string:id>')
def category(id):
    try:
        category = Categories.objects.get(id=ObjectId(id))

        if category.type.lower() == "quick customization":
            return render_template('view/quick_custom.html',
                                   category=category)

        products = list(Products.objects(category=category))
        random.shuffle(products)

    except Categories.DoesNotExist:
        flash("Category Not Found!", category='error')
        return redirect(url_for('routes.store'))

    return render_template('view/category_product.html',
                           category=category,
                           products=products)


# CUSTOMER REVIEW
@routes.route('/write_review', methods=['GET', 'POST'])
def review_form():
    form = ReviewForm()

    if form.validate_on_submit():
        review = Review(
            name=form.name.data,
            title=form.title.data,
            review=form.message.data
        )

        review.save()
        flash("Review Added!", category='success')
        return redirect(url_for('routes.get_reviews'))

    return render_template('view/review_form.html',
                           form=form)


# DISPLAY CUSTOMER REVIEWS
@routes.route('/reviews')
def get_reviews():

    reviews = Review.objects.order_by('-timestamp')
    reviews_count = Review.objects.count()

    for review in reviews:
        review.formatted_date = review.timestamp.strftime("%d %B %Y")

    return render_template('view/reviews.html',
                           reviews=reviews,
                           reviews_count=reviews_count)

web/templates/view/about.html
{% extends 'base.html' %}

{% block body %}
<div class="container-fluid mb-5">

    <div class="container text-center my-3 border-bottom mb-5">
        <h1 class="display-1 fw-bold text-capitalize text-body-tertiary">About Us</h1>
    </div>

    <div class="container">

        <!-- ROW ONE -->
        <div class="row gy-4">
            <div class="col-11 col-sm-10 col-md-6 col-lg-4 text-center mx-auto">
                <img src="{{ url_for('static', filename='images/about-1.jpg') }}" class="img-fluid" width="400" alt="about">
            </div>
            <div class="col-11 col-sm-10 col-md-6 col-lg text-center mx-auto my-md-auto">
                <h5 class="mb-3">Who We Are</h5>
                <p>Welcome to <span class="fw-semibold">MiniArt!</span> We are a passionate team dedicated to creating
                    unique, handcrafted items and stunning paintings. Every piece is thoughtfully designed and carefully
                    crafted, ensuring high quality, originality, and a personal touch. Our love for handmade artistry
                    shines through in everything we create, bringing warmth and creativity into every product.</p>
            </div>
        </div>

        <!-- BREAK SPACE -->
        <div class="py-5"></div>

        <!-- ROW TWO -->
        <div class="row gy-4">
            <div class="col-11 col-sm-10 d-md-none text-center mx-auto">
                <img src="{{ url_for('static', filename='images/about-2.jpg') }}" class="img-fluid" width="400" alt="about">
            </div>
            <div class="col-11 col-sm-10 col-md-6 col-lg text-center mx-auto my-md-auto">
                <h5 class="mb-3">Our Mission</h5>
                <p>
                    At <span class="fw-semibold">MiniArt</span>, we believe in the charm and authenticity of handmade goods. Our mission is to craft beautiful, meaningful pieces that bring joy to our customers and enhance their spaces. Whether you're searching for a unique gift or something special for yourself, our collection offers something truly one-of-a-kind.
                    <p class="text-break">
                    We take pride in our craftsmanship, ensuring that every product reflects the passion, dedication, and artistry that define our brand. Thank you for supporting handmade artistry and small businesses — we couldn’t do this without you!</p>
                </p>
            </div>
            <div class="d-none d-md-block col-md-6 col-lg-4 text-center mx-auto">
                <img src="{{ url_for('static', filename='images/about-2.jpg') }}" class="img-fluid" width="400" alt="about">
            </div>
        </div>

        <!-- BREAK SPACE -->
        <div class="py-5 my-5"></div>

        <div class="row">
            <div class="col-11 col-sm-10 col-md-6 col-lg text-center mx-auto my-md-auto">
                <h4 class="fw-semibold text-body-tertiary">Happy Shopping!</h4>
                <h6 class="fst-italic fw-normal text-body-tertiary">@MiniArt!</h6>
            </div>
        </div>
    </div>

</div>

<!-- BREAK SPACE -->
<div class="py-5"></div>
{% endblock %}

web/templates/view/add_product.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <h1 class="display-5 text mb-5 fw-bold text-capitalize text-center">Add Product</h1>
    
    <div class="container-fluid form-signin w-100 m-auto">
        <form method="POST">
            {{ form.hidden_tag() }}

            <div class="form-floating my-2">
                {{ form.title(type="text", class="form-control", id="title", placeholder="") }}
                {{ form.title.label(for="title") }}
            </div>
            <div class="form-floating my-2">
                {{ form.price(type="number", class="form-control", id="price", placeholder="") }}
                {{ form.price.label(for="price") }}
            </div>
            <div class="form-floating my-2">
                {{ form.img_urls(class="form-control", rows="5", id="img", placeholder="", style="height: 150px;") }}
                {{ form.img_urls.label(for="img") }}

            </div>
            <div class="form-floating my-2">
                {{ form.detail(class="form-control", rows="5", id="detail", placeholder="", style="height: 150px;") }}
                {{ form.detail.label(for="detail") }}
            </div>
            <div class="form-floating my-2">
                {{ form.category_id(class="form-select", id="category_id",) }}
                {{ form.category_id.label(for="category_id") }}
            </div>
            <div class="form-check mt-4 pt-2">
                {{ form.bestseller(type="checkbox", class="form-check-input", id="bestseller") }}
                {{ form.bestseller.label(for="bestseller", class="form-check-label") }}
            </div>

            <div class="my-3"></div>

            {{ form.add(class="btn btn-sm btn-success px-4", type="submit") }}

            <a href="{{ url_for('root.inventory') }}" class="btn btn-sm btn-secondary ps-2 pe-3 my-3 text-uppercase">
                <i class="bi bi-chevron-left"></i> To Inventory
            </a>
        </form>
    </div>
</div>
{% endblock %}

web/templates/view/category_product.html
{% extends 'base.html' %}

{% block body %}
<div class="container-fluid">

    <div class="container text-center my-3 border-bottom">
        <h1 class="display-1 fw-bold text-capitalize text-body-tertiary"><a href="{{ url_for('routes.store') }}" class="text-body-tertiary link-underline link-underline-opacity-0">Store</a></h1>
    </div>

    <!-- PANEL TITLE  -->
    <div class="container-fluid my-5 text-center">
        <h6 class="text-uppercase text-body-tertiary">{{ category.type }}</h6>
    </div>

    {% if products %}
    <div class="row gy-3 mx-md-5 px-md-3 px-lg-5">
        {% for product in products %}

        <div class="col-6 col-md-4 col-lg-3 col-xl-2 d-flex">
            
            <div class="card border m-1 w-100 product-card shadow-sm card-hover-pop">

                <a href="{{ url_for('routes.item', id=product.id) }}" class="link-dark link-underline-opacity-0">

                    {% if product.img_urls|length > 1 %}
                    <!-- CAROUSEL FOR MULTIPLE IMAGES -->
                    <div id="productImagesCarousel{{ product.id }}" class="carousel slide" data-bs-ride="carousel">
                        <div class="carousel-inner">
                            {% for url in product.img_urls %}
                            <div class="carousel-item {% if loop.first %}active{% endif %}">
                                <img src="{{ url }}" class="img-fluid product-img" alt="Product Image">
                            </div>
                            {% endfor %}
                        </div>
                        <button class="carousel-control-prev" type="button"
                            data-bs-target="#productImagesCarousel{{ product.id }}" data-bs-slide="prev">
                            <i class="bi bi-arrow-left-short text-body-tertiary fw-lighter display-6 d-none d-lg-block"></i>
                        </button>
                        <button class="carousel-control-next" type="button"
                            data-bs-target="#productImagesCarousel{{ product.id }}" data-bs-slide="next">
                            <i
                                class="bi bi-arrow-right-short text-body-tertiary fw-lighter display-6 d-none d-lg-block"></i>
                        </button>
                    </div>

                    {% elif product.img_urls|length == 1 %}
                    <!-- SINGLE IMAGE -->
                    <img src="{{ product.img_urls[0] }}" class="img-fluid product-img" alt="product">

                    {% else %}
                    <!-- NO IMAGE -->
                    <p class="text-muted text-center py-4">No image available</p>
                    {% endif %}

                    <div class="mt-3 px-1">
                        <p class="px-1 m-0 text-capitalize fw-medium">{{ product.title }}</p>
                        <p class="px-1 mt-3 mb-0 ms-0 me-0 fw-semibold">₹{{ product.price }}</p>
                    </div>
                </a>

            </div>
        </div>

        {% endfor %}
    </div>

    {% else %}

    <div class="container-fluid text-center py-5">
        <h1 class="display-1 fw-bold mt-5 pt-5 text-capitalize text-danger">Products Not Found!</h1>
        <p class="text-capitalize mb-5 pb-5 text-danger-emphasis">Sorry! There are no products listed in this category!
        </p>
    </div>

    {% endif %}

</div>
{% endblock %}

web/templates/view/change_user_password.html
{% extends 'base.html' %}

{% block content %}
<div class="container">

    {% if form.errors %}
    {% for field, errors in form.errors.items() %}
    {% for error in errors %}
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
        {{ error }}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
    {% endfor %}
    {% endfor %}
    {% endif %}

    <h1 class="display-5 text mb-5 fw-bold text-capitalize text-center">
        Change User → {{ user_password_reset.name }} Password!
    </h1>

    {% if current_user.id == user_password_reset.id or current_user.username == "admin" %}
    <div class="container-fluid form-signin w-100 m-auto">
        <form method="POST" action="{{ url_for('auth.reset_password', id=user_password_reset.id) }}">
            {{ form.hidden_tag() }}

            <div class="form-floating my-2">
                {{ form.reset_password_hash(type="password", class="form-control", id="password", placeholder="") }}
                {{ form.reset_password_hash.label(for="password") }}
            </div>
            
            <div class="form-floating my-2">
                {{ form.reset_password_hash2(type="password", class="form-control", id="password2", placeholder="") }}
                {{ form.reset_password_hash2.label(for="password2") }}
            </div>

            <div class="my-3"></div>

            {{ form.reset(class="btn btn-sm btn-success px-3", type="submit") }}

            <a href="{{ url_for('auth.update_user', id=user_password_reset.id) }}"
                class="btn btn-sm btn-secondary ps-2 pe-3 text-uppercase" , type="button">
                <i class="bi bi-chevron-left"></i> Back
            </a>
        </form>
    </div>

    {% else %}
    <div class="container-fluid text-center py-5">
        <h1 class="display-1 fw-bold mt-5 pt-5 text-capitalize text-danger">Unauthorized Access!</h1>
        <p class="text-capitalize mb-5 pb-5 text-danger-emphasis">Sorry! You Don't Have Access To That User Profile.</p>
    </div>

    {% endif %}
</div>
{% endblock %}

web/templates/view/dashboard.html
{% extends 'base.html' %}

{% block content %}
<div class="container-fluid">
    <div>
        <h1 class="display-5 text mb-5 fw-bold text-capitalize text-center">Dashboard</h1>
    </div>

    <div class="col-9 card mx-auto">
        <h3 class="card-header text-uppercase text-center">{{ current_user.name }}</h3>
        <div class="card-body">

            <p class="card-text border rounded p-2">
                <span class="fw-medium">User ID →</span>
                {{ current_user.id }}
            </p>

            <p class="card-text border rounded p-2">
                <span class="fw-medium">Name →</span>
                {{ current_user.name }}
            </p>

            <p class="card-text border rounded p-2">
                <span class="fw-medium">Username →</span>
                {{ current_user.username }}
            </p>

            <p class="card-text border rounded p-2">
                <span class="fw-medium">Email →</span>
                {{ current_user.email }}
            </p>

            <a href="{{ url_for('auth.update_user', id=current_user.id) }}"
                class="btn btn-sm btn-success px-4 w-100 text-uppercase">
                Edit <i class="bi bi-pencil-square"></i>
            </a>
        </div>
    </div>

    <div class="col-10 mx-auto d-flex flex-column align-items-center flex-md-row justify-content-md-start my-5">

        {% if current_user.username == "admin" %}
        <div class="card shadow-sm my-2 w-75">
            <div class="card-header fw-semibold text-center">Current Users</div>
            <div class="card-body text-center">
                <h5 class="card-title mb-3">{{ users_count }} Users</h5>
                <a href="{{ url_for('auth.users') }}" class="text-capitalize">User List <i class="bi bi-arrow-right-short"></i></a>
            </div>
        </div>
        {% endif %}
    
        <div class="card shadow-sm my-2 w-75 mx-md-3">
            <div class="card-header fw-semibold text-center">Current Inventory</div>
            <div class="card-body text-center">
                <h5 class="card-title mb-3">{{ products_count }} Items</h5>
                <a href="{{ url_for('root.inventory') }}" class="text-capitalize">Inventory <i class="bi bi-arrow-right-short"></i></a>
            </div>
        </div>

        <div class="card shadow-sm my-2 w-75">
            <div class="card-header fw-semibold text-center">Current Categories</div>
            <div class="card-body text-center">
                <h5 class="card-title mb-3">{{ category_count }} Categories</h5>
                <a href="{{ url_for('root.list_categories') }}" class="text-capitalize">Categories <i class="bi bi-arrow-right-short"></i></a>
            </div>
        </div>
        
    </div>
</div>


{% endblock %}

web/templates/view/item.html
{% extends 'base.html' %}

{% block body %}
<div class="container-fluid">

    <div class="container text-center my-3 border-bottom">
        <h1 class="display-6 fw-bold text-capitalize text-body-tertiary"><a
                href="{{ url_for('routes.category', id=item.category.id) }}"
                class="text-body-tertiary link-underline link-underline-opacity-0">{{ item.category.type }}</a></h1>
    </div>

    <div class="container-fluid mt-5">

        <div class="container text-center my-5">
            <h6 class="text-uppercase text-body-tertiary">Porduct Details</h6>
        </div>

        <div class="container">

            <div class="row">
                <!-- ITEM IMAGE -->
                <div class="col-12 col-sm-8 col-md-7 mx-auto text-center mt-3 mb-5">

                    {% if item.img_urls|length > 1 %}
                    <!-- CAROUSEL FOR MULTIPLE IMAGES -->
                    <div id="itemImagesCarousel{{ item.id }}" class="carousel slide" data-bs-ride="carousel">

                        <div class="carousel-indicators">
                            {% for url in item.img_urls %}
                            <button type="button" data-bs-target="#itemImagesCarousel{{ item.id }}"
                                data-bs-slide-to="{{ loop.index0 }}" class="{% if loop.first %}active{% endif %}"
                                aria-current="{% if loop.first %}true{% endif %}" aria-label="Slide {{ loop.index }}">
                            </button>
                            {% endfor %}
                        </div>

                        <div class="carousel-inner">
                            {% for url in item.img_urls %}
                            <div class="carousel-item {% if loop.first %}active{% endif %}">
                                <img src="{{ url }}" class="img-fluid mb-2 fixed-img" alt="item Image">
                            </div>
                            {% endfor %}
                        </div>
                        <button class="carousel-control-prev" type="button"
                            data-bs-target="#itemImagesCarousel{{ item.id }}" data-bs-slide="prev">
                            <i
                                class="bi bi-arrow-left-short text-body-tertiary fw-lighter display-6 d-none d-lg-block"></i>
                        </button>
                        <button class="carousel-control-next" type="button"
                            data-bs-target="#itemImagesCarousel{{ item.id }}" data-bs-slide="next">
                            <i
                                class="bi bi-arrow-right-short text-body-tertiary fw-lighter display-6 d-none d-lg-block"></i>
                        </button>
                    </div>

                    {% elif item.img_urls|length == 1 %}
                    <!-- SINGLE IMAGE -->
                    <img src="{{ item.img_urls[0] }}" class="img-fluid mb-2 fixed-img" alt="item">

                    {% else %}
                    <!-- NO IMAGE -->
                    <p class="text-muted">No image available</p>
                    {% endif %}

                </div>

                <!-- ITEM TITLE -->
                <div class="col-12 col-sm-8 col-md-7 mx-auto text-center mb-3">
                    <h1 class="text-capitalize fw-medium fs-6">{{ item.title }}</h1>
                </div>

                <!-- ITEM DETAILS -->
                <div class="col-12 col-sm-8 col-md-6 mx-auto">
                    <table class="table table-sm table-borderless">
                        <tbody>
                            <tr>
                                <td class="text-end"><span class="text-body-tertiary">Price</span></td>
                                <td class="ps-2 ps-md-5"><span class="fw-semibold fst-italic fs-5">₹{{ item.price
                                        }}</span></td>
                            </tr>
                            <tr>
                                <td class="text-end"><span class="text-body-tertiary">Description</span></td>
                                <td class="ps-2 ps-md-5">{{ item.detail }}</td>
                            </tr>
                        </tbody>
                    </table>
                </div>

                <!-- ORDER ITEM -->
                <div class="col-12 col-sm-8 col-md-7 mx-auto text-center my-4">
                    <a href="https://wa.me/917798010393?text={{
                            (
                                'Hello! I would like to place an order for the following item:\n\n'
                                ~ 'Product image: ' ~ item.img_urls[0] ~ '\n\n'
                                ~ item.title ~ '\n\n'
                                ~ 'Price: ₹' ~ ('{:.2f}'.format(item.price)) ~ '\n'
                                ~ 'Quantity: [Enter Quantity]'
                            ) | urlencode
                        }}" 
                        class="btn btn-sm btn-success w-50 text-capitalize shadow">
                        Place <span class="text-lowercase">an</span> Order
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

web/templates/view/reviews.html
{% extends 'base.html' %}

{% block body %}
<div class="container-fluid">

    <div class="container text-center my-3 border-bottom mb-5">
        <h1 class="display-1 fw-bold text-capitalize text-body-tertiary">Happy Customer's</h1>
    </div>

    {% if reviews %}
    <div class="container mb-4">
        <a href="{{ url_for('routes.review_form') }}" class="link-underline link-underline-opacity-0">
            Write a review
        </a>
    </div>

    <div class="container border-bottom mb-4">
       <p>{{ reviews_count }} customer reviews</p>
    </div>

    <div class="container">

        <div class="row">
            {% for review in reviews %}
            <div class="col-12 col-md-4 mb-5">
                <figure>
                    <p class="mb-4">
                        <span class="fw-semibold">
                            {{ review.title }}
                        </span> <br>

                        <span class="review-time-p">
                            Reviewd on {{ review.formatted_date }}
                        </span> <br>

                        {{ review.review }}
                    </p>
                    <figcaption class="blockquote-footer">
                        <cite title="Source Title">{{ review.name }}</cite>
                    </figcaption>
                </figure>
            </div>
            {% endfor %}
        </div>
    </div>

    {% else %}
    <div class="container-fluid text-center py-5">
        <h1 class="display-1 fw-bold mt-5 pt-5 text-capitalize text-danger">No Reviews!</h1>
        <a href="{{ url_for('routes.review_form') }}" class="link-underline link-underline-opacity-50 link-offset-2">
            Write a <span class="">review</span> now!
        </a>
    </div>

    {% endif %}

</div>
{% endblock %}