web/auth.py
from flask import Blueprint, render_template, flash, request, redirect, url_for
from .webforms import UserForm, LoginForm, PasswordForm
from .models import Users
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import login_user, logout_user, login_required, current_user
from mongoengine.errors import DoesNotExist
from bson import ObjectId



auth = Blueprint('auth', __name__)


# LOGIN USER
@auth.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()

    # VALIDATE FORM FOR LOGIN
    if form.validate_on_submit():
        user = Users.objects(username=form.username.data).first()

        if user:
            # CHECK PASSWORD HASH
            if check_password_hash(user.password_hash, form.password.data):
                login_user(user)
                if user.username == "admin":
                    flash("Welcome Admin!", category='success')
                else:
                    flash(f"Welcome {user.username} - Logged In!", category='success')
                return redirect(url_for('root.dashboard'))
            else:
                flash("Wrong Password! - Try Again", category='error')
        else:
            flash("Invalid Username!", category='error')

        # CLEAR FORM
        form.username.data = ''

    return render_template('view/login.html',
                           form=form)


# LOGOUT USER
@auth.route("/logout")
@login_required
def logout():
    logout_user()
    flash("Logged Out!", category='success')
    return redirect(url_for('routes.home'))


# REGISTER USER
@auth.route('/register', methods=['GET', 'POST'])
@login_required
def register():
    name = None
    form = UserForm()

    # CHECK IF ADMIN
    if current_user.username == "admin": 
    # VALIDATE FORM DATA
        if form.validate_on_submit():
            # QUERY DB FOR CHECKING IF USER ALREADY EXISTS
            user = Users.objects(username=form.username.data).first()
            
            if user is None:
                # HASH PASSWORD
                hashed_pw = generate_password_hash(form.password_hash.data)

                # USER DATA TO INSERT INTO DB
                user = Users(name=form.name.data,
                            username=form.username.data,
                            email=form.email.data,
                            password_hash=hashed_pw)
                
                # INSERT RECORD INTO DB
                user.save()

            # ASSIGN NAME VALUE
            name = form.name.data

            # CLEAR FORM
            form.name.data = ''
            form.username.data = ''
            form.email.data = ''

            # RETURN A MESSAGE
            flash("User Registered!", category='success')
            return redirect(url_for('auth.users'))

        our_users = Users.objects.order_by('-date_added')

        return render_template('view/register.html',
                            form=form,
                            name=name,
                            our_users=our_users)
    
    else:
        flash("Sorry! You Are Not Authorized For This Action...", category='error')
        return redirect(url_for('root.dashboard'))


# EDIT/UPDATE USER
@auth.route('/user/<string:id>/update', methods=['GET', 'POST'])
@login_required
def update_user(id):
    form = UserForm()

    try:
        name_to_update = Users.objects.get(id=ObjectId(id))
    except DoesNotExist:
        flash("User not found", category='error')
        return redirect(url_for('root.dashboard'))

    if request.method == 'POST':

        name_to_update.name = request.form['name']
        name_to_update.username = request.form['username']
        name_to_update.email = request.form['email']

        try:
            name_to_update.save()
            flash("User Updated!", category='success')
            return redirect(url_for('root.dashboard'))

        except:
            flash("Error Updating User!", category='error')
            return render_template('view/update_user.html',
                                form=form,
                                name_to_update=name_to_update)
    else:
        return render_template('view/update_user.html',
                            form=form,
                            name_to_update=name_to_update,
                            id=id)
    

# DELETE USER
@auth.route('/user/<string:id>/delete')
@login_required
def delete_user(id):

    # ONLY ADMIN AND THE SPECIFIC ID USER CAN DELETE THEIR PROFILE
    if str(current_user.id) == id or current_user.username == 'admin':
        try:
            user_to_delete = Users.objects.get(id=ObjectId(id))
            user_to_delete.delete()

            if current_user.username == 'admin':
                flash("User Deleted!", category='success')
                return redirect(url_for('auth.users'))
            else:
                logout_user()
                flash("Account Deleted! Logged Out!", category='success')
                return redirect(url_for('routes.home'))

        except DoesNotExist:
            flash("User Not Found!", category='error')
            return redirect(url_for('auth.users'))
        
    else:
        flash("You Don't Have Access To This User", category='error')
        return redirect(url_for('root.dashboard'))


# RESET USER PASSWORD
@auth.route('/user/<string:id>/password-reset', methods=['GET', 'POST'])
@login_required
def reset_password(id):
    form = PasswordForm()

    try:
        user_password_reset = Users.objects.get(id=ObjectId(id))
    except DoesNotExist:
        flash("User Not Found", category='error')
        return redirect(url_for('auth.users'))

    if form.validate_on_submit():
        reset_hashed_pw = generate_password_hash(form.reset_password_hash.data)

        user_password_reset.password_hash = reset_hashed_pw

        try:
            user_password_reset.save()
            flash("Password Changed!", category='success')
            return redirect(url_for('root.dashboard'))
        
        except:
            flash("Error Changing Password!", category='error')
            return render_template('view/change_user_password.html',
                                   form=form)

    else:
        return render_template('view/change_user_password.html',
                           form=form,
                           id=id,
                           user_password_reset=user_password_reset)
    

# DISPLAY ALL USERS
@auth.route('/users')
@login_required
def users():

    # GET ALL EXISTING USERS FROM DB
    users = Users.objects.order_by('-date_added')

    return render_template('view/display_users.html',
                           users=users)

web/routes.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from .models import Products, Feedback, Categories, Review
from .webforms import FeedbackForm, ReviewForm
from mongoengine.errors import DoesNotExist
from bson import ObjectId
import random
from datetime import datetime



routes = Blueprint('routes', __name__)


# HOME PAGE
@routes.route('/')
def home():

    bestsellers = Products.objects.order_by('title')
    reviews = Review.objects()[:2]

    return render_template('view/home.html',
                           bestsellers=bestsellers,
                           reviews=reviews)


# INDIVIDUAL PRODUCT
@routes.route('/item/<string:id>')
def item(id):

    # GET PRODUCT BY ID
    try:
        item = Products.objects.get(id=ObjectId(id))
    except DoesNotExist:
        flash("Product not found!", category='error')
        return redirect(url_for('routes.home'))

    return render_template('view/item.html',
                           item=item)


# ABOUT US PAGE
@routes.route('/about')
def about():
    return render_template('view/about.html')


# CONTACT US PAGE
@routes.route('/contact', methods=['GET', 'POST'])
def contact():
    form = FeedbackForm()

    if form.validate_on_submit():
        feedback = Feedback(name=form.name.data,
                            phone_number=form.phone_number.data,
                            message=form.message.data)
        
        feedback.save()
        flash("Feedback Submitted!", category='success')
        return redirect(url_for('routes.contact'))

    return render_template('view/contact.html',
                           form=form)


# STORE PAGE
@routes.route('/store')
def store():

    categories = list(Categories.objects())

    first_category = None
    other_categories = []

    for category in categories:
        if category.type.lower() == "quick customization":
            first_category = category
        else:
            other_categories.append(category)

    if first_category:
        ordered_categories = [first_category] + other_categories
    else:
        ordered_categories = other_categories

    return render_template('view/store.html',
                           category=ordered_categories)


# PRODUCT UNDER A CATEGORY
@routes.route('/category/<string:id>')
def category(id):
    try:
        category = Categories.objects.get(id=ObjectId(id))

        if category.type.lower() == "quick customization":
            return render_template('view/quick_custom.html',
                                   category=category)

        products = list(Products.objects(category=category))
        random.shuffle(products)

    except Categories.DoesNotExist:
        flash("Category Not Found!", category='error')
        return redirect(url_for('routes.store'))

    return render_template('view/category_product.html',
                           category=category,
                           products=products)


# CUSTOMER REVIEW
@routes.route('/write_review', methods=['GET', 'POST'])
def review_form():
    form = ReviewForm()

    if form.validate_on_submit():
        review = Review(
            name=form.name.data,
            title=form.title.data,
            review=form.message.data
        )

        review.save()
        flash("Review Added!", category='success')
        return redirect(url_for('routes.get_reviews'))

    return render_template('view/review_form.html',
                           form=form)


# DISPLAY CUSTOMER REVIEWS
@routes.route('/reviews')
def get_reviews():

    reviews = Review.objects.order_by('-timestamp')
    reviews_count = Review.objects.count()

    for review in reviews:
        review.formatted_date = review.timestamp.strftime("%d %B %Y")

    return render_template('view/reviews.html',
                           reviews=reviews,
                           reviews_count=reviews_count)

web/templates/about.html
{% extends 'base.html' %}

{% block body %}
<div class="container-fluid mb-5">

    <div class="container text-center my-3 border-bottom mb-5">
        <h1 class="display-1 fw-bold text-capitalize text-body-tertiary">About Us</h1>
    </div>

    <div class="container">

        <!-- ROW ONE -->
        <div class="row gy-4">
            <div class="col-11 col-sm-10 col-md-6 col-lg-4 text-center mx-auto">
                <img src="{{ url_for('static', filename='images/about-1.jpg') }}" class="img-fluid" width="400" alt="about">
            </div>
            <div class="col-11 col-sm-10 col-md-6 col-lg text-center mx-auto my-md-auto">
                <h5 class="mb-3">Who We Are</h5>
                <p>Welcome to <span class="fw-semibold">MiniArt!</span> We are a passionate team dedicated to creating
                    unique, handcrafted items and stunning paintings. Every piece is thoughtfully designed and carefully
                    crafted, ensuring high quality, originality, and a personal touch. Our love for handmade artistry
                    shines through in everything we create, bringing warmth and creativity into every product.</p>
            </div>
        </div>

        <!-- BREAK SPACE -->
        <div class="py-5"></div>

        <!-- ROW TWO -->
        <div class="row gy-4">
            <div class="col-11 col-sm-10 d-md-none text-center mx-auto">
                <img src="{{ url_for('static', filename='images/about-2.jpg') }}" class="img-fluid" width="400" alt="about">
            </div>
            <div class="col-11 col-sm-10 col-md-6 col-lg text-center mx-auto my-md-auto">
                <h5 class="mb-3">Our Mission</h5>
                <p>
                    At <span class="fw-semibold">MiniArt</span>, we believe in the charm and authenticity of handmade goods. Our mission is to craft beautiful, meaningful pieces that bring joy to our customers and enhance their spaces. Whether you're searching for a unique gift or something special for yourself, our collection offers something truly one-of-a-kind.
                    <p class="text-break">
                    We take pride in our craftsmanship, ensuring that every product reflects the passion, dedication, and artistry that define our brand. Thank you for supporting handmade artistry and small businesses — we couldn’t do this without you!</p>
                </p>
            </div>
            <div class="d-none d-md-block col-md-6 col-lg-4 text-center mx-auto">
                <img src="https://placehold.co/100" class="img-fluid" width="400" alt="about">
            </div>
        </div>

        <!-- BREAK SPACE -->
        <div class="py-5 my-5"></div>

        <div class="row">
            <div class="col-11 col-sm-10 col-md-6 col-lg text-center mx-auto my-md-auto">
                <h4 class="fw-semibold text-body-tertiary">Happy Shopping!</h4>
                <h6 class="fst-italic fw-normal text-body-tertiary">@MiniArt!</h6>
            </div>
        </div>
    </div>

</div>

<!-- BREAK SPACE -->
<div class="py-5"></div>
{% endblock %}

web/templates/add_category.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <div class="container-fluid form-signin w-100 m-auto">
        <form method="POST">
            {{ form.hidden_tag() }}

            <h1 class="display-5 text mb-5 fw-normal text-capitalize text-center">Add Category</h1>

            <div class="form-floating my-2">
                {{ form.type(type="text", class="form-control", id="type", placeholder="") }}
                {{ form.type.label(for="type") }}
            </div>

            <div class="my-3"></div>

            {{ form.create(class="btn btn-sm btn-success px-4", type="submit") }}

            <a href="{{ url_for('root.list_categories') }}" class="btn btn-sm btn-secondary ps-2 pe-3 my-3 text-uppercase">
                <i class="bi bi-chevron-left"></i> To Category List
            </a>
        </form>
    </div>
</div>
{% endblock %}

web/templates/base.html
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>MiniArt</title>

    <link rel="icon" type="image/png" href="{{ url_for('static', filename='images/icon_logo.png') }}">

    <!-- CDN LINKS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">

    <!-- GOOGLE FONT -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Courgette&family=Merienda:wght@300..900&display=swap" rel="stylesheet">

    <!-- STATIC CSS -->
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
</head>

<body>

    <!-- MAIN NAVBAR -->
    <nav class="navbar navbar-expand-xl bg-dark border-bottom border-body" data-bs-theme="dark">
        <div class="container-fluid">

            <a class="navbar-brand" href="
            {% if current_user.is_authenticated %}
                {{ url_for('root.dashboard') }}
            {% else %}
                {{ url_for('routes.home') }}
            {% endif %}">
                MiniArt
            </a>


            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mx-auto mb-2 mb-lg-0 w-100">

                    {% if current_user.is_authenticated %}

                    <!-- WHEN LOGIN DISPLAY THESE LINKS -->
                    <div class="d-xl-flex justify-content-xl-center w-100">
                        <li class="nav-item mx-xl-3">
                            <a class="nav-link" href="{{ url_for('root.dashboard') }}">Dashboard</a>
                        </li>
                        <li class="nav-item mx-xl-3">
                            <a class="nav-link" href="{{ url_for('root.list_categories') }}">Category</a>
                        </li>
                        <li class="nav-item mx-xl-3">
                            <a class="nav-link" href="{{ url_for('root.inventory') }}">Inventory</a>
                        </li>
                        <li class="nav-item mx-xl-3">
                            <a class="nav-link" href="{{ url_for('root.add_category') }}">Add Category</a>
                        </li>
                        <li class="nav-item mx-xl-3">
                            <a class="nav-link" href="{{ url_for('root.add_product') }}">Add Product</a>
                        </li>

                        {%if current_user.username == "admin" %}
                        <li class="nav-item mx-xl-3">
                            <a class="nav-link" href="{{ url_for('auth.register') }}">Register User</a>
                        </li>
                        <li class="nav-item mx-xl-3">
                            <a class="nav-link" href="{{ url_for('auth.users') }}">Users</a>
                        </li>
                        {% endif %}

                    </div>


                    <li class="nav-item mx-xl-3 my-xl-auto">
                        <a class="btn btn-danger px-4 my-3 my-xl-0" href="{{ url_for('auth.logout') }}">Logout</a>
                    </li>

                    {% else %}

                    <div class="d-xl-flex justify-content-xl-end w-100">
                        <li class="nav-item mx-xl-3">
                            <a class="nav-link" href="{{ url_for('routes.home') }}">Home</a>
                        </li>
                        <li class="nav-item mx-xl-3">
                            <a class="nav-link" href="{{ url_for('routes.store') }}">Store</a>
                        </li>
                        <li class="nav-item mx-xl-3">
                            <a class="nav-link" href="{{ url_for('routes.get_reviews') }}">Reviews</a>
                        </li>
                        <li class="nav-item mx-xl-3">
                            <a class="nav-link" href="{{ url_for('routes.about') }}">About Us</a>
                        </li>
                        <li class="nav-item ms-xl-3">
                            <a class="nav-link" href="{{ url_for('routes.contact') }}">Contact Us</a>
                        </li>
                    </div>

                    <!-- WHEN LOGOUT DISPLAY THESE LINKS -->
                    <!-- <li class="nav-item mx-xl-3 my-xl-auto">
                        <a class="btn btn-success px-4 my-3 my-xl-0" href="{{ url_for('auth.login') }}">Login</a>
                    </li> -->

                    {% endif %}

                </ul>
            </div>
        </div>
    </nav>


    <!-- FLASH MESSAGES -->
    <div class="container my-1">
        {% with messages = get_flashed_messages(with_categories=true) %}

        {% if messages %}

        {% for category, message in messages %}

        {% if category == 'success' %}
        <div class="alert alert-success alert-dismissible fade show" role="alert">
            {{ message }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>

        {% elif category == 'error' %}
        <div class="alert alert-danger alert-dismissible fade show" role="alert">
            {{ message }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>

        {% elif category == 'warning' %}
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
            {{ message }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>

        {% else %}
        <div class="alert alert-info alert-dismissible fade show" role="alert">
            {{ message }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>

        {% endif %}

        {% endfor %}

        {% endif %}

        {% endwith %}
    </div>


    <!-- MAIN BODY CONENT -->

    {% if current_user.is_authenticated %}
    <div class="my-5">
        {% block content %}
        {% endblock %}
    </div>

    {% else %}

    <div class="mb-5">
        {% block body %}
        {% endblock %}
    </div>

    {% endif %}


    <!-- MAIN FOOTER -->

    {% if current_user.is_authenticated %}

    <footer class="mt-auto bg-body-tertiary">
        <div class="footer container-fluid py-5 text-center">
            <span class="my-5 pt-5 text-body-secondary text-center">Copyright © MiniArt 2025.</span>
            <p class=" footer-p text-center text-body-tertiary m-0">designed by
                <a href="https://github.com/p-sher4win" class="link-secondary">p-sher4win</a>
            </p>
        </div>
    </footer>


    {% else %}

    <div class="container-fluid mt-auto bg-dark">
        <footer class="py-3 my-4 text-center">
            <img src="{{ url_for('static', filename='images/miniart_logo.png') }}" width="100" class="my-4 py-4"
                alt="logo">

            <ul class="nav justify-content-center pb-2 mb-2">
                <li class="nav-item mx-1 mx-sm-3 mx-xl-4">
                    <a href="{{ url_for('routes.home') }}" class="nav-link px-2 text-secondary">Home</a>
                </li>
                <li class="nav-item mx-1 mx-sm-3 mx-xl-4">
                    <a href="{{ url_for('routes.store') }}" class="nav-link px-2 text-secondary">Store</a>
                </li>
                <li class="nav-item mx-1 mx-sm-3 mx-xl-4">
                    <a href="{{ url_for('routes.about') }}" class="nav-link px-2 text-secondary">About</a>
                </li>
                <li class="nav-item mx-1 mx-sm-3 mx-xl-4">
                    <a href="{{ url_for('routes.contact') }}" class="nav-link px-2 text-secondary">Contact</a>
                </li>
            </ul>

            <ul class="nav justify-content-center border-bottom pb-3 mb-3">
                <li class="nav-item ">
                    <a href="https://www.instagram.com/_.miniart_03" class="nav-link px-2 text-secondary"><i class="bi bi-instagram"></i></a>
                </li>
                <li class="nav-item ">
                    <a href="https://wa.me/918262800188" class="nav-link px-2 text-secondary"><i class="bi bi-whatsapp"></i></a>
                </li>
                <li class="nav-item ">
                    <a href="mailto:miniart.0623@gmail.com" class="nav-link px-2 text-secondary"><i class="bi bi-envelope-at"></i></a>
                </li>
                <li class="nav-item ">
                    <a href="tel:+918262800188" class="nav-link px-2 text-secondary"><i class="bi bi-telephone"></i></a>
                </li>
            </ul>

            <p class="text-center text-white-50 m-0">Copyright © MiniArt 2025.</p>
            <p class=" footer-p text-white-50 text-center m-0">designed by
                <a href="https://github.com/p-sher4win" class="link-secondary">p-sher4win</a>
            </p>
        </footer>
    </div>

    {% endif %}


    <!-- CDN SCRIPTS -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
        crossorigin="anonymous"></script>

</body>

</html>

web/templates/change_user_password.html
{% extends 'base.html' %}

{% block content %}
<div class="container">

    {% if id == current_user.id or current_user.id == 1 %}

    <div class="container-fluid form-signin w-100 m-auto">
        <form method="POST" action="{{ url_for('auth.reset_password', id=user_password_reset.id) }}">
            {{ form.hidden_tag() }}

            <h1 class="display-5 text mb-5 fw-normal text-capitalize text-center">Change User → {{ user_password_reset.name }} Password!</h1>

            <div class="form-floating my-2">
                {{ form.reset_password_hash(type="password", class="form-control", id="password", placeholder="") }}
                {{ form.reset_password_hash.label(for="password") }}
            </div>
            <div class="form-floating my-2">
                {{ form.reset_password_hash2(type="password", class="form-control", id="password2", placeholder="") }}
                {{ form.reset_password_hash2.label(for="password2") }}
            </div>

            <div class="my-3"></div>

            {{ form.reset(class="btn btn-sm btn-success px-3", type="submit") }}

            <a href="{{ url_for('auth.update_user', id=user_password_reset.id) }}" class="btn btn-sm btn-secondary ps-2 pe-3 text-uppercase", type="button">
                <i class="bi bi-chevron-left"></i> Back
            </a>
        </form>
    </div>

    
    {% else %}

    <div class="container-fluid text-center py-5">
        <h1 class="display-1 fw-bold mt-5 pt-5 text-capitalize text-danger">Unauthorized Access!</h1>
        <p class="text-capitalize mb-5 pb-5 text-danger-emphasis">Sorry! You Don't Have Access To That User Profile.</p>
    </div>


    {% endif %}
    
</div>
{% endblock %}

web/templates/dashboard.html
{% extends 'base.html' %}

{% block content %}
<div class="container-fluid">
    <div>
        <h1 class="display-5 text mb-5 fw-normal text-capitalize text-center">Dashboard</h1>
    </div>

    <div class="col-9 card mx-auto">
        <h3 class="card-header text-uppercase text-center">{{ current_user.name }}</h3>
        <div class="card-body">

            <p class="card-text border rounded p-2">
                <span class="fw-medium">User ID →</span>
                {{ current_user.id }}
            </p>

            <p class="card-text border rounded p-2">
                <span class="fw-medium">Name →</span>
                {{ current_user.name }}
            </p>

            <p class="card-text border rounded p-2">
                <span class="fw-medium">Username →</span>
                {{ current_user.username }}
            </p>

            <p class="card-text border rounded p-2">
                <span class="fw-medium">Email →</span>
                {{ current_user.email }}
            </p>

            <a href="{{ url_for('auth.update_user', id=current_user.id) }}"
                class="btn btn-sm btn-success px-4 w-100 text-uppercase">
                Edit <i class="bi bi-pencil-square"></i>
            </a>
        </div>
    </div>

    <div class="col-10 mx-auto d-flex flex-column align-items-center flex-md-row justify-content-md-start my-5">

        {% if current_user.id == 1 %}
        <div class="card shadow-sm my-2 w-75">
            <div class="card-header fw-semibold text-center">Current Users</div>
            <div class="card-body text-center">
                <h5 class="card-title mb-3">{{ users_count }} Users</h5>
                <a href="{{ url_for('auth.users') }}" class="text-capitalize">User List <i class="bi bi-arrow-right-short"></i></a>
            </div>
        </div>
        {% endif %}
    
        <div class="card shadow-sm my-2 w-75 mx-md-3">
            <div class="card-header fw-semibold text-center">Current Inventory</div>
            <div class="card-body text-center">
                <h5 class="card-title mb-3">{{ products_count }} Items</h5>
                <a href="{{ url_for('root.inventory') }}" class="text-capitalize">Inventory <i class="bi bi-arrow-right-short"></i></a>
            </div>
        </div>

        <div class="card shadow-sm my-2 w-75">
            <div class="card-header fw-semibold text-center">Current Categories</div>
            <div class="card-body text-center">
                <h5 class="card-title mb-3">{{ category_count }} Categories</h5>
                <a href="{{ url_for('root.list_categories') }}" class="text-capitalize">Categories <i class="bi bi-arrow-right-short"></i></a>
            </div>
        </div>
        
    </div>
</div>


{% endblock %}

web/templates/update_user.html
{% extends 'base.html' %}

{% block content %}
<div class="container">

    {% if id == current_user.id or current_user.id == 1 %}

    <div class="container-fluid form-signin w-100 m-auto">
        <form method="POST" action="{{ url_for('auth.update_user', id=name_to_update.id) }}">
            {{ form.hidden_tag() }}

            <h1 class="display-5 text mb-5 fw-normal text-capitalize text-center">Update User</h1>

            <div class="form-floating my-2">
                {{ form.name(type="text", class="form-control", id="name", value=name_to_update.name) }}
                {{ form.name.label(for="name") }}
            </div>
            <div class="form-floating my-2">
                {{ form.username(type="text", class="form-control", id="username", value=name_to_update.username) }}
                {{ form.username.label(for="username") }}
            </div>
            <div class="form-floating my-2">
                {{ form.email(type="email", class="form-control", id="email", value=name_to_update.email) }}
                {{ form.email.label(for="email") }}
            </div>

            <div class="my-3"></div>

            {{ form.update(class="btn btn-sm btn-success px-3 mt-2", type="submit") }}

            {% if name_to_update.id != 1 %}

                <a href="{{ url_for('auth.delete_user', id=name_to_update.id) }}" class="btn btn-sm btn-danger px-4 text-uppercase mx-2 mt-2", type="button">Delete <i class="bi bi-trash3"></i></a>

            {% endif %}

            <a href="{{ url_for('root.dashboard') }}" class="btn btn-sm btn-secondary ps-2 pe-3 text-uppercase mt-2", type="button"><i class="bi bi-chevron-left"></i> To Dashboard</a>

            <div class="d-flex my-4 justify-content-start">
                <span>Forgot password?</span>
                <a href="{{ url_for('auth.reset_password', id=name_to_update.id) }}" class="mx-1", type="button">Change Password</a>
            </div>


        </form>
    </div>

    
    {% else %}

    <div class="container-fluid text-center py-5">
        <h1 class="display-1 fw-bold mt-5 pt-5 text-capitalize text-danger">Unauthorized Access!</h1>
        <p class="text-capitalize mb-5 pb-5 text-danger-emphasis">Sorry! You Don't Have Access To That User Profile.</p>
    </div>

    {% endif %}

</div>
{% endblock %}